"use strict";

const TYPES={FOLLOW:"seguimiento",LAB:"laboratorio"};
const EQUIPMENT={
  daf:{title:"DAF",fields:[["nombre","Nombre equipo",""],["producto","Producto",""],["caudal","Caudal equipo","m³/h"],["dosisPolimero","Dosis polímero","ppm"],["dosisCoagulante","Dosis coagulante","ppm"],["sstAfluente","SST afluente","mg/L"],["sstEfluente","SST efluente","mg/L"],["presionBomba","Presión bomba presurización","bar"],["presionSaturacion","Presión de saturación","bar"],["flujoAire","Flujo de aire","L/min"]]},
  decanter:{title:"Decanter",fields:[["nombre","Nombre equipo",""],["producto","Producto",""],["caudal","Caudal Decanter","m³/h"],["dosisPolimero","Dosis polímero","ppm"],["sstAfluente","SST afluente","mg/L"],["sstEfluente","SST clarificado","mg/L"],["velocidad","Velocidad diferencial","rpm"],["torque","Torque","%"],["inyeccion","Punto de inyección",""],["humedad","Humedad del lodo","%"]]},
  filtro:{title:"Filtro banda",fields:[["nombre","Nombre equipo",""],["producto","Producto",""],["caudal","Caudal equipo","m³/h"],["dosisPolimero","Dosis polímero","ppm"],["consumoPolimero","Consumo de polímero","kg/h"],["sstAfluente","SST afluente","mg/L"],["sstEfluente","SST filtrado","mg/L"],["presionTela","Presión de la tela","bar"]]}
};
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const blankGeneral=()=>({cliente:"",planta:"",fecha:new Date().toISOString().slice(0,10),ingeniero:"Rodrigo Medina",participantes:"",objetivo:"",descripcion:"",observaciones:"",recomendaciones:"",emailCliente:"",cc:"",asunto:"Informe técnico SNF"});
const blankState=()=>({type:null,step:0,general:blankGeneral(),equipment:[],tests:[],photos:[]});
let state=load();
function load(){try{return {...blankState(),...JSON.parse(localStorage.getItem("snfV2")||"null")}}catch{return blankState()}}
function save(){try{localStorage.setItem("snfV2",JSON.stringify(state))}catch{notice("No fue posible guardar. Reduce las fotografías.")}stats()}
function e(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function n(v){const x=Number(String(v??"").replace(",","."));return Number.isFinite(x)?x:0}
function calc(eq){const d=eq.data,caudal=n(d.caudal),sst=n(d.sstAfluente),out=n(d.sstEfluente),dose=n(d.dosisPolimero),cons=n(d.consumoPolimero);return {carga:(caudal*sst/1000).toFixed(2),ratio:(sst?(dose/sst*1000):0).toFixed(2),remocion:(sst?((sst-out)/sst*100):0).toFixed(1),consumo:(cons||caudal*dose/1000).toFixed(2)}}
function dataObj(type){return Object.fromEntries(EQUIPMENT[type].fields.map(([k])=>[k,""]))}
function addEq(type){state.equipment.push({id:uid(),type,application:type==="daf"?"polimero":"",data:dataObj(type)});save();render()}
function addTest(){state.tests.push({id:uid(),muestra:`Muestra ${state.tests.length+1}`,producto:"",dosis:"",sst:"",turbiedad:"",resultado:"",observaciones:""});save();render()}
function field(k,label,kind="input",wide=false){const v=e(state.general[k]);return `<div class="field${wide?" wide":""}"><label>${label}</label>${kind==="textarea"?`<textarea data-g="${k}">${v}</textarea>`:`<input type="${kind}" data-g="${k}" value="${v}">`}</div>`}
function render(){const t=document.querySelector("#tabs"),p=document.querySelector("#pages");if(!t||!p)return;if(!state.type){t.innerHTML="";p.innerHTML=home();bind();stats();return}const labels=state.type===TYPES.FOLLOW?["Inicio","Datos","Equipos","Informe","Correo"]:["Inicio","Datos","Pruebas","Informe","Correo"];t.innerHTML=labels.map((x,i)=>`<button class="${state.step===i?"active":""}" data-step="${i}">${i+1}. ${x}</button>`).join("");p.innerHTML=state.step===0?home():state.step===1?general():state.step===2?(state.type===TYPES.FOLLOW?equipment():laboratory()):state.step===3?reportPage():emailPage();bind();stats()}
function home(){return `<section class="panel"><h2>Seleccione el tipo de visita</h2><p class="muted">El flujo, las tablas y el informe se adaptarán a la opción seleccionada.</p><div class="grid2"><button class="btn primary" data-type="${TYPES.FOLLOW}" style="min-height:110px">Visita de seguimiento</button><button class="btn primary" data-type="${TYPES.LAB}" style="min-height:110px">Pruebas de laboratorio</button></div>${state.type?'<div class="actions"><button class="btn" data-reset>Nueva visita</button></div>':""}</section>`}
function general(){return `<section class="panel"><h2>Datos generales</h2><div class="grid2">${field("cliente","Cliente")}${field("planta","Planta")}${field("fecha","Fecha","date")}${field("ingeniero","Ingeniero")}${field("participantes","Participantes","input",true)}${field("objetivo","Objetivo de la visita","textarea",true)}${field("descripcion","Descripción del trabajo","textarea",true)}</div></section>${photos()}<div class="actions"><button class="btn primary" data-next>Continuar</button></div>`}
function photos(){return `<section class="panel"><h2>Registro fotográfico</h2><label class="btn primary" for="photoFile">Tomar o agregar fotografías</label><input id="photoFile" class="hidden" type="file" accept="image/*" capture="environment" multiple><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-top:14px">${state.photos.length?state.photos.map((x,i)=>`<div><img src="${x.data}" style="width:100%;height:130px;object-fit:cover;border-radius:10px"><input data-pcap="${x.id}" value="${e(x.caption)}" placeholder="Descripción"><button class="btn" data-pdel="${x.id}">Eliminar</button></div>`).join(""):'<p class="muted">Sin fotografías.</p>'}</div></section>`}
function equipment(){return `<section class="panel toolbar"><b>Agregar equipo:</b><button class="btn" data-add="daf">DAF</button><button class="btn" data-add="decanter">Decanter</button><button class="btn" data-add="filtro">Filtro banda</button></section>${state.equipment.map(eqCard).join("")||'<section class="panel"><p class="muted">Agrega uno o más equipos.</p></section>'}<div class="actions"><button class="btn primary" data-next>Generar informe</button></div>`}
function eqCard(eq,idx){const c=calc(eq);let app=eq.type==="daf"?`<div class="field"><label>Aplicación</label><select data-app="${eq.id}"><option value="polimero" ${eq.application==="polimero"?"selected":""}>Polímero</option><option value="coagulante" ${eq.application==="coagulante"?"selected":""}>Coagulante</option><option value="ambos" ${eq.application==="ambos"?"selected":""}>Polímero + coagulante</option></select></div>`:"";let rows=EQUIPMENT[eq.type].fields.filter(([k])=>!(eq.type==="daf"&&k==="dosisPolimero"&&eq.application==="coagulante")&&!(eq.type==="daf"&&k==="dosisCoagulante"&&eq.application==="polimero")).map(([k,l,u])=>`<div class="erow"><span>${l}</span><span>${u}</span><input data-eqid="${eq.id}" data-key="${k}" value="${e(eq.data[k])}" inputmode="decimal"></div>`).join("");return `<section class="equipment"><div class="eqhead"><b>${idx+1}. ${EQUIPMENT[eq.type].title}</b><button class="btn" data-edel="${eq.id}">Eliminar</button></div><div style="background:white;padding:10px">${app}</div>${rows}<div class="subtitle">Cálculos automáticos</div><div class="erow"><span>Carga másica</span><span>kg/h</span><input readonly value="${c.carga}"></div><div class="erow"><span>Ratio polímero / SST</span><span>kg/t SST</span><input readonly value="${c.ratio}"></div><div class="erow"><span>Remoción SST</span><span>%</span><input readonly value="${c.remocion}"></div><div class="erow"><span>Consumo calculado</span><span>kg/h</span><input readonly value="${c.consumo}"></div></section>`}
function laboratory(){return `<section class="panel"><h2>Pruebas de laboratorio</h2><p class="muted">Agrega una fila por muestra o condición ensayada.</p><button class="btn primary" data-addtest>Agregar prueba</button><div style="overflow:auto;margin-top:12px"><table class="report"><thead><tr><th>Muestra</th><th>Producto</th><th>Dosis</th><th>SST</th><th>Turbiedad</th><th>Resultado</th><th>Observaciones</th><th></th></tr></thead><tbody>${state.tests.map(testRow).join("")}</tbody></table></div></section><div class="actions"><button class="btn primary" data-next>Generar informe</button></div>`}
function testRow(x){return `<tr>${["muestra","producto","dosis","sst","turbiedad","resultado","observaciones"].map(k=>`<td><input data-testid="${x.id}" data-tkey="${k}" value="${e(x[k])}"></td>`).join("")}<td><button class="btn" data-tdel="${x.id}">Eliminar</button></td></tr>`}
function reportPage(){return `<section class="panel"><h2>Conclusiones</h2>${field("observaciones","Observaciones","textarea")}${field("recomendaciones","Recomendaciones","textarea")}</section>${report()}<div class="actions"><button class="btn" data-save>Guardar</button><button class="btn" data-print>Guardar como PDF</button><button class="btn primary" data-next>Preparar correo</button></div>`}
function report(){let results=state.type===TYPES.FOLLOW?state.equipment.map((q,i)=>{const c=calc(q);return `<h3>Tabla ${i+1}. ${EQUIPMENT[q.type].title}</h3><table><tbody>${EQUIPMENT[q.type].fields.map(([k,l,u])=>`<tr><td>${l}</td><td>${u}</td><td>${e(q.data[k])||"-"}</td></tr>`).join("")}<tr><td>Carga másica</td><td>kg/h</td><td>${c.carga}</td></tr><tr><td>Ratio</td><td>kg/t SST</td><td>${c.ratio}</td></tr><tr><td>Remoción SST</td><td>%</td><td>${c.remocion}</td></tr></tbody></table>`}).join(""):`<h3>Resultados de laboratorio</h3><table><thead><tr><th>Muestra</th><th>Producto</th><th>Dosis</th><th>SST</th><th>Turbiedad</th><th>Resultado</th><th>Observaciones</th></tr></thead><tbody>${state.tests.map(x=>`<tr>${["muestra","producto","dosis","sst","turbiedad","resultado","observaciones"].map(k=>`<td>${e(x[k])||"-"}</td>`).join("")}</tr>`).join("")}</tbody></table>`;return `<section class="panel"><div class="report" id="report"><b>SNF WATER SCIENCE</b><h2>Informe ${state.type===TYPES.FOLLOW?"de visita de seguimiento":"de pruebas de laboratorio"}</h2><p>${e(state.general.cliente)} · ${e(state.general.planta)} · ${e(state.general.fecha)}</p><h3>Objetivo</h3><p>${e(state.general.objetivo)||"-"}</p><h3>Descripción del trabajo</h3><p>${e(state.general.descripcion)||"-"}</p>${results}${state.photos.length?`<h3>Registro fotográfico</h3><div style="display:grid;grid-template-columns:repeat(2,1fr);gap:10px">${state.photos.map((x,i)=>`<figure><img src="${x.data}" style="width:100%;max-height:270px;object-fit:contain"><figcaption>Imagen ${i+1}. ${e(x.caption)||"Registro de visita"}</figcaption></figure>`).join("")}</div>`:""}<h3>Observaciones</h3><p>${e(state.general.observaciones)||"-"}</p><h3>Recomendaciones</h3><p>${e(state.general.recomendaciones)||"-"}</p></div></section>`}
function emailPage(){return `<section class="panel"><h2>Enviar con Outlook móvil</h2><div class="grid2">${field("emailCliente","Correo del cliente","email")}${field("cc","CC","email")}${field("asunto","Asunto","input",true)}</div><p class="muted">Guarda primero el informe como PDF. Luego abre Outlook móvil y adjunta el PDF desde Descargas.</p><div class="actions"><button class="btn" data-print>Guardar PDF</button><button class="btn primary" data-mobilemail>Abrir Outlook móvil</button></div></section>`}
function bind(){document.querySelectorAll("[data-type]").forEach(b=>b.onclick=()=>{state.type=b.dataset.type;state.step=1;save();render()});document.querySelectorAll("[data-step]").forEach(b=>b.onclick=()=>{state.step=+b.dataset.step;render()});document.querySelector("[data-reset]")?.addEventListener("click",()=>{if(confirm("¿Crear una visita nueva y borrar los datos actuales?")){state=blankState();save();render()}});document.querySelectorAll("[data-g]").forEach(x=>x.oninput=()=>{state.general[x.dataset.g]=x.value;save()});document.querySelector("[data-next]")?.addEventListener("click",()=>{state.step=Math.min(4,state.step+1);render()});document.querySelectorAll("[data-add]").forEach(b=>b.onclick=()=>addEq(b.dataset.add));document.querySelectorAll("[data-eqid]").forEach(x=>x.oninput=()=>{const q=state.equipment.find(z=>z.id===x.dataset.eqid);q.data[x.dataset.key]=x.value;save();render()});document.querySelectorAll("[data-app]").forEach(x=>x.onchange=()=>{state.equipment.find(z=>z.id===x.dataset.app).application=x.value;save();render()});document.querySelectorAll("[data-edel]").forEach(b=>b.onclick=()=>{state.equipment=state.equipment.filter(x=>x.id!==b.dataset.edel);save();render()});document.querySelector("[data-addtest]")?.addEventListener("click",addTest);document.querySelectorAll("[data-testid]").forEach(x=>x.oninput=()=>{state.tests.find(z=>z.id===x.dataset.testid)[x.dataset.tkey]=x.value;save()});document.querySelectorAll("[data-tdel]").forEach(b=>b.onclick=()=>{state.tests=state.tests.filter(x=>x.id!==b.dataset.tdel);save();render()});document.querySelector("#photoFile")?.addEventListener("change",photosInput);document.querySelectorAll("[data-pcap]").forEach(x=>x.oninput=()=>{state.photos.find(z=>z.id===x.dataset.pcap).caption=x.value;save()});document.querySelectorAll("[data-pdel]").forEach(b=>b.onclick=()=>{state.photos=state.photos.filter(x=>x.id!==b.dataset.pdel);save();render()});document.querySelector("[data-save]")?.addEventListener("click",()=>{save();notice("Visita guardada")});document.querySelectorAll("[data-print]").forEach(b=>b.onclick=()=>{if(state.step!==3){state.step=3;render()}setTimeout(()=>window.print(),150)});document.querySelector("[data-mobilemail]")?.addEventListener("click",openMobileOutlook)}
async function photosInput(ev){for(const f of [...ev.target.files]){if(!f.type.startsWith("image/"))continue;state.photos.push({id:uid(),caption:"",data:await resize(f)})}save();render()}
function resize(file){return new Promise((ok,no)=>{const r=new FileReader();r.onerror=no;r.onload=()=>{const im=new Image();im.onerror=no;im.onload=()=>{const s=Math.min(1,1400/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*s);c.height=Math.round(im.height*s);c.getContext("2d").drawImage(im,0,0,c.width,c.height);ok(c.toDataURL("image/jpeg",.76))};im.src=r.result};r.readAsDataURL(file)})}
function openMobileOutlook(){const g=state.general;if(!g.emailCliente.includes("@")){notice("Ingresa un correo válido");return}const body=`Estimado/a:\n\nAdjunto informe técnico correspondiente a la visita realizada en ${g.planta} el ${g.fecha}.\n\nObjetivo:\n${g.objetivo}\n\nObservaciones:\n${g.observaciones}\n\nRecomendaciones:\n${g.recomendaciones}\n\nSaludos cordiales,\n${g.ingeniero}\nSNF Chile`;const q=new URLSearchParams({to:g.emailCliente,cc:g.cc||"",subject:g.asunto||"Informe técnico SNF",body});const deep=`ms-outlook://emails/new?${q}`;window.location.href=deep;setTimeout(()=>notice("Si Outlook no abrió, verifica que Outlook esté instalado."),1800)}
function stats(){const a=document.querySelector("#equipmentCount"),b=document.querySelector("#dataCount"),c=document.querySelector("#recCount");if(a)a.textContent=state.type===TYPES.LAB?state.tests.length:state.equipment.length;if(b)b.textContent=state.type===TYPES.LAB?state.tests.filter(x=>x.resultado).length:state.equipment.reduce((s,x)=>s+Object.values(x.data).filter(Boolean).length,0);if(c)c.textContent=state.general.recomendaciones?"Sí":"No"}
function notice(t){const d=document.createElement("div");d.className="notice";d.textContent=t;document.body.appendChild(d);setTimeout(()=>d.remove(),2400)}
render();if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(console.warn));
